# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         forks
version:      0.07
version_from: lib/forks.pm
installdirs:  site
requires:
    load:                          0.11
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
