#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         forks
version:      0.04
version_from: lib/forks.pm
installdirs:  site
requires:
    load:                          0.03
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
