--- #YAML:1.0
name:               forks
version:            0.31
abstract:           forks - emulate threads with fork
author:
    - Eric Rybski (rybskej@yahoo.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Acme::Damn:           0
    Attribute::Handlers:  0
    Devel::Required:      0.07
    Devel::Symdump:       0
    File::Spec:           0
    if:                   0
    IO::Socket:           1.18
    List::MoreUtils:      0.15
    Scalar::Util:         1.11
    Storable:             0
    Sys::SigAction:       0.11
    Test::More:           0
    Time::HiRes:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
