--- #YAML:1.0
name:                forks
version:             0.27
abstract:            forks - emulate threads with fork
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Attribute::Handlers:           0
    Devel::Required:               0.07
    File::Spec:                    0
    IO::Socket:                    1.18
    List::MoreUtils:               0.15
    Scalar::Util:                  1.09
    Storable:                      0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Eric Rybski (rybskej@yahoo.com)
