--- #YAML:1.0
name:                forks
version:             0.30
abstract:            forks - emulate threads with fork
license:             ~
author:              
    - Eric Rybski (rybskej@yahoo.com)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Attribute::Handlers:           0
    Devel::Required:               0.07
    File::Spec:                    0
    if:                            0
    IO::Socket:                    1.18
    List::MoreUtils:               0.15
    Scalar::Util:                  1.11
    Storable:                      0
    Sys::SigAction:                0.11
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
