# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         forks
version:      0.25
version_from: lib/forks.pm
installdirs:  site
requires:
    Devel::Required:               0.07
    File::Spec:                    0
    IO::Socket:                    1.18
    List::MoreUtils:               0.15
    Scalar::Util:                  1.09
    Storable:                      0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
